### ISSUE TITLE
Connect to open SSID

### ISSUE THREAD

**Issue by zvse** [grokbeer/wifi-to-ethernet#1]
I am wanting to connect to an open SSID, however, it doesn't seem to work. How can I we go about fixing this? I have tried it on a network that has a passkey, and it worked. However, when I am trying to direct it to an open SSID, it will not show up in the fleet dashboard as online.

**Comment by zvse** [comment]
> I am wanting to connect to an open SSID, however, it doesn't seem to work. How can I we go about fixing this? I have tried it on a network that has a passkey, and it worked. However, when I am trying to direct it to an open SSID, it will not show up in the fleet dashboard as online.

To be specific, the connection I am trying to get it to connect to is Open Enhanced.

**Comment by grokbeer** [comment]
Thanks for raising this issue @notequaltoif. I haven't tried to connect a balena device to a Wi-Fi Enhanced Open network before. It's also known as [Opportunistic Wireless Encryption (OWE)](https://en.wikipedia.org/wiki/Opportunistic_Wireless_Encryption).

This isn't really a problem with my project but I'm happy to help you to fix it!

The [WiFi Setup section](https://www.balena.io/docs/reference/OS/network/2.x/#wifi-setup) of the [Networking on balenaOS 2.x documentation](https://www.balena.io/docs/reference/OS/network/2.x/) describes how to modify the WiFi configuration found in the `/system-connections/` folder in the boot partition of your device's SD card.

That documentation doesn't describe how to configure it for OWE but according to the [NetworkManager settings reference](https://developer-old.gnome.org/NetworkManager/stable/settings-802-11-wireless-security.html) you need to change `key-mgmt=wpa-psk`to `key-mgmt=owe`. You probably also want to remove the `psk=...` line.

Hopefully that helps you fix your issue but please comment to let me know if you try it out.

I suggest you raise an issue on https://github.com/balena-io/docs to get their [2.x.md](https://github.com/balena-io/docs/blob/master/shared/network/2.x.md) document updated with instructions for configuring OWE networks.
